### ISSUE TITLE
code?

### ISSUE THREAD

**Issue by dieloz** [EvgenyKashin/stylegan2-distillation#1]
Dear Evgeny,
Do you have plans to release the code? I'm very interested to play with it
Best
Diego

**Comment by EvgenyKashin** [comment]
Hi, thank you for your interest! We plan to publish training datasets, pretrained weights for pix2pixHD, and inference scripts in a few month.

**Comment by dieloz** [comment]
Thanks for your prompt reply. Looking forward to see this pull request!

**Comment by thimabru1010** [comment]
@EvgenyKashin Do you have plans to release the weights for style mixing ??? I am very interested in this application. Seems you have solved a huge problem in style transfer.

**Comment by EvgenyKashin** [comment]
We plan to publish the weights for the gender swap and the style mixing to show the different options for one input image and for two images, respectively

**Comment by yaxingwang** [comment]
@EvgenyKashin congratulation for ECCV2020. You paper is great, when do you publish the code?

**Comment by ofirkris** [comment]
Amazing paper - and congrats on ECCV - Is there a plan to release the code and trained weights?

**Comment by EvgenyKashin** [comment]
Thank you for your feedback. We are ready to post the code, but it just so happens that we will post it by the conference date.  Thank you for your understanding.

**Comment by doantientai** [comment]
Amazing work! We cannot wait to see your source code.

**Comment by JulianPinzaru** [comment]
Hey, is there any video presentation of the conference you've attended? I would really enjoy to watch it. Hopefully you can share a link. 
P.S. looks like people are really excited to see your code

**Comment by BEpresent** [comment]
Really cool project ! Would also be very interested in the code and examples for training on custom datasets, pix2pixHD style  domain_A -> domain_B  :) Most work in this field is applied to unpaired image to image translation (as it is much easier to get a dataset for this), but there is real demand for paired image to image translation (many questions in the SPADE repo), but it seems that since pix2pixHD there have not been many improvements?

**Comment by EvgenyKashin** [comment]
You are absolutely correct, it's so. In general it's just the tricky way to get a paired dataset to train pix2pix like networks. 

Also I would like to apologize to everyone who is waiting for the code - I couldn't think before that it is so difficult to get an approve from a large company. The funny thing is that the code is actually very primitive. But at least now I understand many authors who don't release a code right after the paper, even if it is ready for release long ago. We are still hoping to release the code and we look forward to your understanding!

**Comment by EvgenyKashin** [comment]
Hi everyone, we have released the code and the dataset, but the weights have not yet been agreed. I hope we can release the weights later. Suggest your pool requests, if you find it useful

**Comment by ofirkris** [comment]
> Hi everyone, we have released the code and the dataset, but the weights have not yet been agreed. I hope we can release the weights later. Suggest your pool requests, if you find it useful

Amazing work!
How much time did it take to train? How many epochs?

**Comment by EvgenyKashin** [comment]
Thank you! The training time of Pix2pixHD is about 2 days on 2x2080ti gpus. In terms of pix2pix iterations  - the results look good from 1kk iterations. But it may be necessary to start training several times from scratch to get to the best local optima.
