### ISSUE TITLE
Style Mixing

### ISSUE THREAD

**Issue by nouraIT** [EvgenyKashin/stylegan2-distillation#10]
Hello, 

Could you please explain more how to run Style Mixing please. 

Thank you

**Comment by EvgenyKashin** [comment]
Hi, have you checked readme about "Style mixing" (Crl+F) already?

**Comment by nouraIT** [comment]
yes but I need more help if you got the time. Thank you

**Comment by EvgenyKashin** [comment]
Have your tried to run it already? You need to generate style mixed images like in https://github.com/NVlabs/stylegan2 example and save source images(which were used into mixing) and mixed results. Do you have any error messages?

**Comment by nouraIT** [comment]
First I want to know what is the command for the style mixing

**Comment by nouraIT** [comment]
testing not training

**Comment by nouraIT** [comment]
I want to give the pre-trained model two images to mix them

**Comment by BrianPulfer** [comment]
Dear Evgeny,

I am also experiencing some problems training a model for style mixing.

I have generated style and content images with stylegan2, and put them in folders 'train_A' and 'train_C', while the results of style mixing are put in folder 'train_B'. However, when i launch the train.py script with the `--input_nc 6` option, I get the following error:

`RuntimeError: Given groups=1, weight of size [64, 6, 7, 7], expected input[1, 3, 518, 518] to have 6 channels, but got 3 channels instead`

as if only images from folder A (train_A) where used as Input.

Could you please let me know the exact folder structure needed for training? That would be much appreciated.

Here's mine:
<img width="244" alt="Schermata 2020-11-15 alle 18 46 15" src="https://user-images.githubusercontent.com/42559439/99192392-e2d07780-2772-11eb-895b-6591f6888449.png">

**Comment by EvgenyKashin** [comment]
Hi, I agree - stack trace looks like only one input image was used. You folder structure looks correctly. Could you try to debug from this line https://github.com/EvgenyKashin/stylegan2-distillation/blob/ce3d1f2476688eb71f83e7404bfe5deae415a1a9/pix2pixHD/data/aligned_dataset.py#L56 please? I also will try, but probably not in nearest week

**Comment by BrianPulfer** [comment]
Thank you for your prompt answer.

It turns out that using the official NVIDIA's repository of pix2pixHD (https://github.com/NVIDIA/pix2pixHD) was the problem. I assumed it would have made no difference.

Using the version provided in this repository (which handles the C folder) fixed the problem for me.

**Comment by molo32** [comment]
can someone upload the pre-trained model to mix styles?
