### ISSUE TITLE
env

### ISSUE THREAD

**Issue by BenfenYU** [EvgenyKashin/stylegan2-distillation#11]
Hi, thanks for your share~
Do you use some virtual environment like conda ?
If yes, could you please share it like using a *.yaml ?

**Comment by EvgenyKashin** [comment]
Hi, we used the pix2pixHD [requirements](https://github.com/EvgenyKashin/stylegan2-distillation/tree/master/pix2pixHD#installation) for env and the StyleGAN2 [Dockerfile](https://github.com/EvgenyKashin/stylegan2-distillation/tree/master/stylegan2#requirements)

**Comment by BenfenYU** [comment]
Well, thanks for your reply~
Could you please tell me the face classification network you use ?

**Comment by EvgenyKashin** [comment]
An internal one, but any other from github should work fine as well

**Comment by BenfenYU** [comment]
ok and thank you ~
