### ISSUE TITLE
can someone share their pre-trained weights?

### ISSUE THREAD

**Issue by molo32** [EvgenyKashin/stylegan2-distillation#12]
I'd like to play with this but I don't have a hardware to train with.
someone who has trained this, can share their weights, I would appreciate it

**Comment by EvgenyKashin** [comment]
It would be cool if somebody will share their experiments! But anyway you could use google Colab for training - it is free.

**Comment by EvgenyKashin** [comment]
We have updated readme with [two sets of weights](https://github.com/EvgenyKashin/stylegan2-distillation/commit/f9133d72f042116aa927668914fbf4954e08cceb)
