### ISSUE TITLE
What is the data.tsv?

### ISSUE THREAD

**Issue by zqx1609** [EvgenyKashin/stylegan2-distillation#13]
when I use Learn_direction_in_latent_space.ipynb to find a direction in dlatents, I don't have the data.tsv file, Can you tell me what is that?

**Comment by EvgenyKashin** [comment]
Hi, it's labelling for a synthetic data by any classifier that you like. It could be an open source gender classifier or age classifier or any other attribute classifier's predictions.

**Comment by zqx1609** [comment]
Thank you so much! Could you tell me where can I get an open source gender classifier?

**Comment by EvgenyKashin** [comment]
https://azure.microsoft.com/en-gb/services/cognitive-services/face/ is random link from google, but definitely there are a lot of examples in github
