### ISSUE TITLE
No such file or directory: 'checkpoints/r512_smile_big_v2/latest_net_G.pth'

### ISSUE THREAD

**Issue by ahmetdadak** [EvgenyKashin/stylegan2-distillation#14]
Hello, 
I am trying to run your Model_infer.ipynb file on Colab but I got this error: No such file or directory: 'checkpoints/r512_smile_big_v2/latest_net_G.pth'. I couldn't find such a directory as the error mentioned actually. I think you have written that it was going to be announced later, is it so? If so, can you provide the date you will release it? I am looking forward to work on this repository.

**Comment by EvgenyKashin** [comment]
Hello, thank you.

You are right, there weren't any weights. But right know we have finally released [two sets of weights](https://github.com/EvgenyKashin/stylegan2-distillation/commit/f9133d72f042116aa927668914fbf4954e08cceb)
