### ISSUE TITLE
Dataset not available

### ISSUE THREAD

**Issue by GurovNik** [EvgenyKashin/stylegan2-distillation#15]
Дропбокс не давал скачать датасет. А сейчас Линка вообще протухла (404). Можно как-то получить доступ к данным?

**Comment by EvgenyKashin** [comment]
Now it's on Gdrive and should work better

**Comment by 8secz-johndpope** [comment]
close

**Comment by AMEERAZAM08** [comment]
where is the link of Data.tsv
