### ISSUE TITLE
Model_infer.ipynb

### ISSUE THREAD

**Issue by yagizcolak** [EvgenyKashin/stylegan2-distillation#16]
I believe the Model_infer.ipynb notebook is not complete. Will you release it any time soon?

**Comment by EvgenyKashin** [comment]
Not exactly. It's finished, but it was lack of weights in our repo. But right know we have finally released [it](https://github.com/EvgenyKashin/stylegan2-distillation/commit/f9133d72f042116aa927668914fbf4954e08cceb)
