### ISSUE TITLE
What is this noise in the generated images?

### ISSUE THREAD

**Issue by 0x454447415244** [EvgenyKashin/stylegan2-distillation#18]
What is this noise in the generated images (the dark circular area)? How to remove it?

![epoch080_synthesized_image](https://user-images.githubusercontent.com/4967138/101995451-8d847900-3cd2-11eb-95ac-a00db84fb706.jpg)
![epoch096_synthesized_image](https://user-images.githubusercontent.com/4967138/101995462-9d03c200-3cd2-11eb-86ca-aa00602daf87.jpg)
![epoch104_synthesized_image](https://user-images.githubusercontent.com/4967138/101995465-a8ef8400-3cd2-11eb-8a33-3eadd3143dd7.jpg)
![epoch081_synthesized_image](https://user-images.githubusercontent.com/4967138/101995493-d50b0500-3cd2-11eb-924d-96cd8f6c8498.jpg)

**Comment by EvgenyKashin** [comment]
It's well known pix2pixHD's artefacts, you could look at https://github.com/NVIDIA/pix2pixHD/issues/46 

> How to remove it?

You could try a different image2image model for the distillation, for example [SPADE](https://github.com/NVlabs/SPADE)

**Comment by 0x454447415244** [comment]
Thanks. I will look into that. As far as I know, SPADE doesn't support image-to-image translation.

**Comment by 8secz-johndpope** [comment]
Nvidia labs solved this with stylegan2-ada 
https://github.com/nvlabs/stylegan2-ada
pytorch version coming soon. 

To get this code working with stylegan2-ada is trivial - just need to drop in the dnnlib folder 

Here's some video discussing noise.
https://youtu.be/7eEom1X1thA?t=365

I built an updated tensorflow2 compatibility mode fork here - 
https://github.com/johndpope/stylegan2-ada

**Comment by EvgenyKashin** [comment]
Thanks @8secz-johndpope !

**Comment by AugustLee93** [comment]
> Thanks. I will look into that. As far as I know, SPADE doesn't support image-to-image translation.

Same issue occures on my model for pix2pixHD, do you have any idea how to solve it ? Or do you have a better image2image model to recommend? Any helps will be appreciated! Thanks

**Comment by EvgenyKashin** [comment]
Hey, you could check [TSIT repo](https://github.com/EndlessSora/TSIT)
