### ISSUE TITLE
Latent space not perfectly disentangled

### ISSUE THREAD

**Issue by kpagels** [EvgenyKashin/stylegan2-distillation#2]
I really like your work and am looking forward to try the code out when you release it. I have one question and I hope you would like to answer. 

You write the following:

"StyleGAN2 latent space is not per- fectly disentangled, so the transformations made by our network are not per- fectly pure. Despite the latent space is not disentangled enough to make pure transformations, impurities are not so severe"

What does it mean that the latent space is not perfectly disentangled? Could you elaborate on that?

**Comment by EvgenyKashin** [comment]
Thanks for your feedback. The basic idea is that some directions are highly correlated and movement along one causes movement along some other. For example, it can be seen that translation into female faces can also add smile. One more example: the age direction associated with glasses.

**Comment by kpagels** [comment]
Thanks @EvgenyKashin for elaborating. That makes sense.
