### ISSUE TITLE
Questions regarding training Pix2PixHD

### ISSUE THREAD

**Issue by Nerdyvedi** [EvgenyKashin/stylegan2-distillation#21]
Hi, I have the following doubts. 

I am training Pix2Pix for 1024 input, Should the loadSize still be 512 or should I change it to 1024?

Would using batch size of 2 instead of 8 result in performance deterioration?

Thank you.

**Comment by EvgenyKashin** [comment]
Hi, I think `loadSize` should be 1024 as your input. Batch size of size 2 looks to small for descent results, you could try Instance Norm instead

**Comment by Nerdyvedi** [comment]
@EvgenyKashin Thanks. Pix2PixHD uses Instance normalisation by default.
