### ISSUE TITLE
Generated Images Datasets

### ISSUE THREAD

**Issue by ofir-dl** [EvgenyKashin/stylegan2-distillation#22]
Hi,

I would like to create a dataset of images generated with interfacegan method.
This dataset should be as varied as possible (i.e age, gender, pose, etc combinations) and does not have to be tagged.

I can use your code to generate the images myself but before doing it I was wondering if such a dataset already exists?
I saw that you supplied gender swap dataset. What about other latent space directions dataset?

Thanks!

**Comment by EvgenyKashin** [comment]
Hi, sorry, we don't provide any other datasets. Most likely they were removed after we finished our experiments. Of course it would be interesting to compare with interfacegan's generated dataset
