### ISSUE TITLE
How to use Learn_direction_in_latent_space.ipynb

### ISSUE THREAD

**Issue by shouramo** [EvgenyKashin/stylegan2-distillation#26]
Hi,

I am just wondering, how am I supposed to use Learn_direction_in_latent_space.ipynb?

What should "data.tsv" be? How should I organize my data here?

Thanks!

**Comment by EvgenyKashin** [comment]
Hey, good question.

I agree that right now it is't clear. After using the `stylegan2/run_generator.py` (as in the readme) you will get images and latents with names like `100.npy` and `100.png` (according to [this](https://github.com/EvgenyKashin/stylegan2-distillation/blob/f9133d72f042116aa927668914fbf4954e08cceb/stylegan2/run_generator.py#L121) line). 

After using your attributes classifier you have to create `data.tsv` with **key** column representing index of generated image (`100` in the example above). And with **label** column that in our example in the notebook contains male/female labels.

Hope it would help!

**Comment by shouramo** [comment]
Thanks for such a quick response! 

So, I would have 2 columns; the first indicating the index (just numbers), the second indicating the attribute label(gender, age, etc.)

For the attributes classifier, which one did you use? I know of deepFace and that works pretty well from my experience, but just curious which you have used to create your `data.tsv`! 

I am using my own styleGAN for this that I trained to generate 256x256 images, corresponding to (14,512) latent outputs, so the directions provided [[stylegan2directions](https://github.com/EvgenyKashin/stylegan2-distillation/tree/master/stylegan2directions)] unfortunately do not work for me.

Thanks!

**Comment by EvgenyKashin** [comment]
Yep, I see. We used internal attributes classifier from my previous company Yandex. But for now I would recommend to use [CLIP classifier](https://github.com/openai/CLIP). It's pretty easy to create a classifier by just describing it. For example, a prompt like "image of a smiling face" and "image of a neutral face" to classify emotions.

**Comment by shouramo** [comment]
Amazing! Thank you so much for all of this info.

Take care,
Moaz
