### ISSUE TITLE
the "Synthetic dataset for gender swap" is the images generated by stylegan2 as you mentioned in the paper or generated by Pix2pixHD?

### ISSUE THREAD

**Issue by YSL0226** [EvgenyKashin/stylegan2-distillation#27]
Hi
Thank you for your great work.
Could I know the "Synthetic dataset for gender swap" is the images generated by stylegan2 as you mentioned in the paper or generated by Pix2pixHD?

**Comment by EvgenyKashin** [comment]
Hey, thanks! Yep, that images generated by SG2 and suitable for training img2img on it

**Comment by YSL0226** [comment]
Thank you for your reply!
