### ISSUE TITLE
Manipulating real/already generated images

### ISSUE THREAD

**Issue by shouramo** [EvgenyKashin/stylegan2-distillation#28]
Hi again! 

I have a quick question: If I have already generated an image using ` python run_generator.py generate-images-custom `, and I want to apply another transformation to that same image (for example, I changed the gender of the image using my own attribute directions, then I want to also change the age with another attribute latent vector). How can I do that?

Thanks!
Moaz

**Comment by EvgenyKashin** [comment]
Hey!

One of possible ways(the simplest) could be adding few more lines of code [here](https://github.com/EvgenyKashin/stylegan2-distillation/blob/f9133d72f042116aa927668914fbf4954e08cceb/stylegan2/run_generator.py#L96) - with one more vector addition

**Comment by shouramo** [comment]
It worked! I really appreciate the fast and clear replies.

Thank you
