### ISSUE TITLE
pix2pix training details

### ISSUE THREAD

**Issue by VladimirGl** [EvgenyKashin/stylegan2-distillation#3]
Can you please provide any details on pix2pixHD parameters / modifications used to train models?
I'm trying to train some models using similar procedure (generate pairs from stylegan), but if use vanila pix2pixHD settings results are not so good.

**Comment by EvgenyKashin** [comment]
Hi, all of our results in the article are taken from vanilla pix2pixHD with default setting:
```
python train.py --name r512_experiment_name --label_nc 0 \
 --dataroot data_folder --tf_log --no_instance \
 --loadSize 512  --gpu_ids 0,1 --batchSize 8
```
You should probably pay more attention to data filtering. For example, if you are performing gender transformation, then filtering by the confidence of the gender classifier can be very helpful. Also, increasing the volume of the dataset also helps.

**Comment by VladimirGl** [comment]
Works for me, thanks! Only difference I have in my initial experiments is default batchSize=1.
