### ISSUE TITLE
Is there a way to combine directions?

### ISSUE THREAD

**Issue by delebash** [EvgenyKashin/stylegan2-distillation#31]
Example: To generate images with a smile you use the smile.py
direction_path ../stylegan2directions/smile.npy

Now what if I wanted a person that was male and had a smile.

Do I have to run each individually or can I combine the generation in one step?

**Comment by EvgenyKashin** [comment]
Hey, yep, I think it could be easy done [here](https://github.com/EvgenyKashin/stylegan2-distillation/blob/a0d9ec3e97b71a07c8f90b8582fa7178ead06da2/stylegan2/run_generator.py#L62). Load two vectors and add them to each other for a linear combination, mb with coefficients.

**Comment by delebash** [comment]
What is mb with coefficients?  Is that something I have to do after adding the two numpy arrays together? TY

**Comment by EvgenyKashin** [comment]
Sorry, lol, I meant "maybe"

**Comment by delebash** [comment]
Lol, Thanks!
