### ISSUE TITLE
What does the Fitting transform and pix2pixHD do?

### ISSUE THREAD

**Issue by delebash** [EvgenyKashin/stylegan2-distillation#32]
So if I create a smile images what is pix2pixHD doing?  When creating the pix2pixHD do I have to train first or is it pretrained for the stylegan2directions. TY

**Comment by EvgenyKashin** [comment]
It just has to be trained from scratch on such images. A main point in training pix2pix, that after training it's possible to add a smile to an image in one forward pass(fast), without using StyleGAN

**Comment by delebash** [comment]
Thanks!
