### ISSUE TITLE
Would it be difficult to convert this to use stylegan2-ada-pytorch

### ISSUE THREAD

**Issue by delebash** [EvgenyKashin/stylegan2-distillation#33]
If not can you give me some pointers on how to do it?  TY

**Comment by EvgenyKashin** [comment]
It should be the same process, "ada" is just an additional augmentation for faster StyleGAN training.

Our method may use any already trained StyleGAN. All in all, you need to find a needed direction in your StyleGAN checkpoint, generate a paired dataset (with and without added vector) and train pix2pix on it.

**Comment by delebash** [comment]
How do you convert this project to use pytorch only without tensorflow?

**Comment by EvgenyKashin** [comment]
The repo that you mentioned is exactly PyTorch.

But current StyleGAN2 repo that I used is also [supporting](https://github.com/rosinality/stylegan2-pytorch/blob/bef283a1c24087da704d16c30abc8e36e63efa0e/train.py#L403) adaptive augmentation(ada) by the way.

**Comment by delebash** [comment]
Ok thanks!
