### ISSUE TITLE
Comparsion with CycleGAN

### ISSUE THREAD

**Issue by ShawnBIT** [EvgenyKashin/stylegan2-distillation#4]
Hi, thanks for your interesting work. I got a question about the comparison method of the gender swap task. I am wondering why you did not compare your method with CycleGAN, which is a popular baseline of unpair image-to-image translation task. Look forward to your reply.

**Comment by EvgenyKashin** [comment]
Hey, thanks for the feedback! Initially, in their paper they did not solve the problem of changing faces, like for example in StarGAN. I think StarGAN is no less popular baseline for unpair image-to-image translation in faces domain. However, we tried CycleGAN at the beginning, but the results were very bad. It also had a small output resolution

**Comment by ShawnBIT** [comment]
Thank you for your reply. I got it.
