### ISSUE TITLE
about attributes predictor

### ISSUE THREAD

**Issue by wyhsirius** [EvgenyKashin/stylegan2-distillation#5]
Hi, very impressive work ! 
Is there any possibility to share your attributes predictor or indicate which predictors you used in the paper ?
Thanks a lot.

**Comment by EvgenyKashin** [comment]
Hi, thanks a lot! We used an internal classifier and because of that it's impossible to share it, but you could use an open source one, for example https://github.com/droidadroit/age-and-gender-classification
