### ISSUE TITLE
aging dataset

### ISSUE THREAD

**Issue by ChengBinJin** [EvgenyKashin/stylegan2-distillation#6]
@EvgenyKashin 
Thank you for your great gender-swap dataset! Would you mind sharing the Aging dataset too?

**Comment by EvgenyKashin** [comment]
Hi, thanks. Sorry, but unfortunately, we didn't plan to publish it (it hasn't been preserved)

**Comment by ChengBinJin** [comment]
@EvgenyKashin Ok, I see thank you!
