### ISSUE TITLE
Download failed

### ISSUE THREAD

**Issue by ChengBinJin** [EvgenyKashin/stylegan2-distillation#7]
@EvgenyKashin 
I want to download your gender-dataset in Dropbox, but it shows "The zip file is too large" and failed to download. Can you zip the file or separately save on several folders as the FFHQ dataset? 
Hopes to hear from you.

**Comment by EvgenyKashin** [comment]
Hi, could your try the Dropbox api(console, desktop gui)?

**Comment by ChengBinJin** [comment]
@EvgenyKashin Ok, I will try to use the desktop version to download again. Thank you again!
